INSTITUTIONS_MAPPING = {
    'massachusetts institute of technology': 'mit',
    'uc berkeley': 'university of california berkeley',
    'the university of texas at austin': 'university of texas at austin',
    'ut austin': 'university of texas at austin',
    'csail mit': 'mit',
    'uc san diego': 'university of california san diego',
    'google inc': 'google',
    'google, inc': 'google',
    'google nyc': 'google',
    'google research ny': 'google research',
    'google research new york': 'google research',
    'and google research israel': 'google research',
    'google brain robotics': 'google brain',
    'research at google mountain view ca': 'google',
    'indiana university (70) bloomington in usa': 'indiana university',
    '() google research new york ny': 'google research',
    'google deepmind london': 'deepmind',
    'google new york': 'google',
    'google deepmind uk': 'deepmind',
    'google inc venice ca usa': 'google',
    'mit csail': 'mit',
    'the ohio state university': 'ohio state university',
    'the university of tokyo': 'university of tokyo',
    'technion': 'technion - israel institute of technology',
    'technion – israel institute of technology': 'technion - israel institute of technology',
    'technion israel': 'technion - israel institute of technology',
    'the technion - israel institute of technology': 'technion - israel institute of technology',
    'the technion': 'technion - israel institute of technology',
    'the technion haifa israel': 'technion - israel institute of technology',
    'technion haifa israel': 'technion - israel institute of technology',
    'technion—israel institute of technology': 'technion - israel institute of technology',
    'department of computer science technion - israel institute of technology':
    'technion - israel institute of technology',
    'the technion – israel institute of technology': 'technion - israel institute of technology',
    'ucla': 'university of california los angeles',
    'uiuc': 'university of illinois at urbana-champaign',
    'cmu': 'carnegie mellon university',
    'école polytechnique fédérale de lausanne switzerland': 'epfl',
    'école polytechnique fédérale de lausanne': 'epfl',
    'école polytechnique fédérale de lausanne (epfl)': 'epfl',
    'epfl lausanne switzerland': 'epfl',
    'epfl switzerland': 'epfl',
    '0 lausanne epfl switzerland': 'epfl',
    'cvlab epfl': 'epfl',
    'mpi for intelligent systems': 'max planck institute for intelligent systems',
    'eth zurich switzerland': 'eth zürich',
    'dept of computer science eth zurich': 'eth zürich',
    'eth zürich switzerland': 'eth zürich',
    'd-bsse eth zurich': 'eth zürich',
    'eecs university of california merced': 'university of california merced',
    'university of california at davis': 'university of california davis',
    'department of computer science university of california irvine':
    'university of california irvine',
    'university of california berkeley berkeley ca 970': 'university of california berkeley',
    'the university of texas at dallas': 'university of texas at dallas',
    'university of texas austin': 'university of texas at austin',
    'the university of texas at austin usa': 'university of texas at austin',
    'ut austin dept of computer sciences': 'university of texas at austin',
    'department of computer science ut austin': 'university of texas at austin',
    'ece dept ut austin': 'university of texas at austin',
    'mccombs school of business the university of texas at austin': 'university of texas at austin',
    'ut at austin usa': 'university of texas at austin',
    'the university of texas at arlington': 'university of texas at arlington',
    'university of texas at austin usa': 'university of texas at austin',
    'the university of texas at austin austin tx 787 usa': 'university of texas at austin',
    'ece university of texas at austin': 'university of texas at austin',
    'department of computer science university of texas austin': 'university of texas at austin',
    'dept of computer science university of texas austin': 'university of texas at austin',
    'university of texas austin tx usa': 'university of texas at austin',
    'university of texas at asutin': 'university of texas at austin',
    'university of texasaustin tx usa': 'university of texas at austin',
    'department of computer science & engineering university of texas at arlington':
    'university of texas at arlington',
    'tencent ai lab university of texas at arlington': 'university of texas at arlington',
    'university of texas at arlington arlington tx 769': 'university of texas at arlington',
    'mccombs school of business university of texas at austin': 'university of texas at austin',
    'one utsa circle university of texas at san antonio san antonio tx 789-6':
    'university of texas at san antonio',
    'school of biomedical informatics university of texas houston tx 77':
    'university of texas at houston',
    'uc irvine': 'university of california irvine',
    'stanford university ca': 'stanford university',
    'computer science department stanford university stanford ca 9': 'stanford university',
    'computer science department stanford university stanford ca 9 usa': 'stanford university',
    'stanford university stanford ca': 'stanford university',
    'stanford graduate school of business': 'stanford university',
    'uc santa barbara': 'university of california santa barbara',
    'uc santa barbara ca usa': 'university of california santa barbara',
    'uc santa cruz': 'university of california santa cruz',
    'uc berkeley department of electrical engineering and computer sciences':
    'university of california berkeley',
    'uc berkeley eecs & icsi': 'university of california berkeley',
    'uc berkeley eecs and icsi': 'university of california berkeley',
    'uc berkeley and qut': 'university of california berkeley',
    'dept of eecs and statistics uc berkeley': 'university of california berkeley',
    'department of psychology uc berkeley': 'university of california berkeley',
    'simons institute uc berkeley': 'university of california berkeley',
    'university of california berkeley berkeley ca 97': 'university of california berkeley',
    'eecs department uc berkeley': 'university of california berkeley',
    'uc san diego la jolla ca 99': 'university of california san diego',
    'cse uc san diego': 'university of california san diego',
    'uc san diego la jolla usa': 'university of california san diego',
    'computer science uc irvine': 'university of california irvine',
    'ics uc irvine': 'university of california irvine',
    'uc los angeles': 'university of california los angeles',
    'yahoo! research santa clara ca usa': 'yahoo! research',
    'qut': 'queensland university of technology',
    'university of california san diego cse': 'university of california san diego',
    'department of psychology university of california san diego':
    'university of california san diego',
    'university of california san deigo': 'university of california san diego',
    'ece department uc santa barbara': 'university of california santa barbara',
    'electrical and computer engineering department university of california los angeles':
    'university of california los angeles',
    'department of computer science university of california los angeles':
    'university of california los angeles',
    'department of computer science ucla los angeles ca 99': 'university of california los angeles',
    'university of southern california los angeles ca 989': 'university of california los angeles',
    'university of california los angles': 'university of california los angeles',
    'biomagnetic imaging lab uc san francisco': 'university of california san francisco',
    'sloan-swartz center for theoretical neurobiology ucsf san francisco ca 9':
    'university of california san francisco',
    'university of california  irvine': 'university of california irvine',
    'university of california at irvine': 'university of california irvine',
    'z department of computer science university of california davis usa':
    'university of california davis',
    'department of mathematics uc davis usa': 'university of california davis',
    'helen wills neuroscience institute uc berkeley': 'university of california berkeley',
    'uc berekely': 'university of california berkeley',
    'computer science division university of california berkeley':
    'university of california berkeley',
    'uc berkeley department of electrical engineering and computer science':
    'university of california berkeley',
    'dept of eecs uc berkeley': 'university of california berkeley',
    'a department of electrical engineering and computer science uc berkeley':
    'university of california berkeley',
    '⇧ university of california berkeley': 'university of california berkeley',
    'computer sciences uc berkeley': 'university of california berkeley',
    'uc berkeley department of statistics': 'university of california berkeley',
    'department of cognitive and brain sciences university of california berkeley ca':
    'university of california berkeley',
    'electrical engineering & computer science and statistics university of california berkeley':
    'university of california berkeley',
    'university of california – berkeley': 'university of california berkeley',
    'b department of statistics uc berkeley': 'university of california berkeley',
    'google brain ca usa': 'google brain',
    'google brain google inc mountain view ca 9': 'google brain',
    'b google research mountain view ca 9': 'google research',
    '8neurosciences phd program stanford university stanford ca 9': 'stanford university',
    '9department of psychology stanford university stanford ca 9': 'stanford university',
    'department of computer science stanford university stanford ca 9': 'stanford university',
    'slac national accelerator laboratory stanford university stanford ca 99 usa':
    'stanford university',
    'neurosciences phd program stanford university stanford ca 9': 'stanford university',
    'department of neurobiology stanford university stanford ca 9': 'stanford university',
    'department of applied physics stanford university stanford ca 9': 'stanford university',
    'department of electrical engineering stanford university stanford ca 9': 'stanford university',
    'nec laboratories america inc cupertino ca': 'nec corporation',
    'nec labs america cupertino ca 9': 'nec corporation',
    'nec laboratories america cupertino ca 99': 'nec corporation',
    'vmware research ca usa': 'vmware research',
    'uc merced': 'university of california merced',
    'ece dept uc san diego': 'university of california san diego',
    'dept of comp sci stanford university stanford ca 9 usa': 'stanford university',
    'stanford university palo alto ca 9': 'stanford university',
    'university of california at berkeley ca usa': 'university of california berkeley',
    'uc berkeley eecs and icsi berkeley ca': 'university of california berkeley',
    'department of computer science and engineering university of california san diego':
    'university of california san diego',
    'uc davis': 'university of california davis',
    'adobe research ca': 'adobe research',
    'adobe research seattle': 'adobe research',
    'university of montreal': 'universite de montreal',
    'university of montreal (mila)': 'universite de montreal',
    'universite de montreal cifar fellow': 'universite de montreal',
    'google research brain team': 'google brain',
    'google ai': 'google',
    'facebook artiﬁcial intelligence research': 'facebook ai research',
    'facebook paris': 'facebook',
    'facebook inc': 'facebook',
    'department of computer science stanford university': 'stanford university',
    'computer science department stanford university': 'stanford university',
    'department of electrical engineering stanford university': 'stanford university',
    'psychology dept stanford': 'stanford university',
    'department of applied physics stanford university': 'stanford university',
    'stanford universty': 'stanford university',
    'stanford ms&e': 'stanford university',
    'eecs mit': 'mit',
    'eecs & csail mit': 'mit',
    'department of eecs mit': 'mit',
    'mit lincoln laboratory': 'mit',
    'mit eecs': 'mit',
    'mit lids': 'mit',
    'mit media lab': 'mit',
    'mit computer science and artiﬁcial intelligence laboratory': 'mit',
    'cbmm mit': 'mit',
    'lcsl iit & mit usa': 'mit',
    'computer science and artiﬁcial intelligence laboratory mit': 'mit',
    'department of brain and cognitive sciences mit': 'mit',
    'bcs mit': 'mit',
    'dept eecs mit': 'mit',
    'mit probabilistic computing project': 'mit',
    'mit sloan school of management': 'mit',
    'carnegie mellon university usa': 'carnegie mellon university',
    'school of computer science carnegie mellon university': 'carnegie mellon university',
    'robotics institute carnegie mellon university': 'carnegie mellon university',
    'carnegie mellon': 'carnegie mellon university',
    'the university of sydney darlington nsw 8 australia': 'university of sydney',
    'university of technology sydney': 'university of sydney',
    'the university of sydney': 'university of sydney',
    'amazon research': 'amazon',
    'amazon inc': 'amazon',
    'amazon research tübingen': 'amazon',
    'amazon rekognition': 'amazon',
    'microsoft research india': 'microsoft research',
    'microsoft research asia': 'microsoft research',
    'microsoft research ai': 'microsoft research',
    'microsoft research cambridge': 'microsoft research',
    'microsoft research new england': 'microsoft research',
    'microsoft research nyc': 'microsoft research',
    'microsoft research redmond': 'microsoft research',
    'microsoft research new york': 'microsoft research',
    'microsoft': 'microsoft research',
    'microsoft research cambridge uk': 'microsoft research',
    'microsoft research beijing china': 'microsoft research',
    'and microsoft research': 'microsoft research',
    'microsoft redmond': 'microsoft research',
    'microsoft research bangalore india': 'microsoft research',
    'microsoft research bangalore': 'microsoft research',
    'microsoft maluuba': 'microsoft research',
    'microsoft research montréal': 'microsoft research',
    'microsoft research new york ny': 'microsoft research',
    'microsoft research new york ny usa': 'microsoft research',
    'visual geometry group university of oxford': 'university of oxford',
    'university of oxford uk': 'university of oxford',
    'vgg department of engineering science university of oxford': 'university of oxford',
    'oxford university': 'university of oxford',
    'department of statistics university of oxford uk': 'university of oxford',
    'dept of statistics university of oxford': 'university of oxford',
    'university of oxford oxford uk': 'university of oxford',
    'harvard medical school': 'harvard university',
    'seas harvard university': 'harvard university',
    'twitter and harvard seas': 'harvard university',
    'harvard university twitter': 'harvard university',
    'eth zurich': 'eth zürich',
    'department of computer science eth zurich': 'eth zürich',
    'ecole polytechnique federale de lausanne': 'epfl',
    'lausanne epfl switzerland': 'epfl',
    'idiap école polytechnique fédérale de lausanne': 'epfl',
    'cornell tech': 'cornell university',
    'department of computer science cornell university': 'cornell university',
    'cs cornell university': 'cornell university',
    'bernstein center for computational neuroscience tubingen': 'university of tübingen',
    'eberhard karls university tubingen': 'university of tübingen',
    'university of tubingen': 'university of tübingen',
    'max planck institute for intelligent systems': 'max planck institute',
    'mpi for biological cybernetics': 'max planck institute',
    'max planck institute for biological cybernetics': 'max planck institute',
    'max planck institute': 'max planck institute',
    'mpi for intelligent systems tubingen': 'max planck institute',
    'max planck institute for biolog cybernetics': 'max planck institute',
    'max planck institutes tubingen germany': 'max planck institute',
    'max planck institute for informatics': 'max planck institute',
    'mpi for software systems': 'max planck institute',
    'max planck institute for human development': 'max planck institute',
    'max planck institutes': 'max planck institute',
    'max planck institute for informatics saarbrucken germany': 'max planck institute',
    'mpi tübingen': 'max planck institute',
    'max planck institute for intelligent systems tubingen germany': 'max planck institute',
    'max planck institute for biological cybernetics tubingen germany': 'max planck institute',
    'mpi-sws': 'max planck institute',
    'mpi-is tubingen': 'max planck institute',
    'university of colorado boulder': 'university of colorado',
    'colorado school of mines': 'university of colorado',
    'colorado state university': 'university of colorado',
    'university of colorado': 'university of colorado',
    '? dept of computer science university of colorado': 'university of colorado',
    'max-planck insitute for medical research': 'max planck institute',
    'max-planck institute for computer science': 'max planck institute',
    'universita degli studi di milano italy': 'universita degli studi di milano',
    'universita degli studi di milano': 'universita degli studi di milano',
    'università degli studi di milano': 'universita degli studi di milano',
    'dsi universita degli studi di milano': 'universita degli studi di milano',
    'politecnico di milano italy': 'politecnico di milano',
    'university of wisconsin madison': 'university of wisconsin - madison',
    'university of wisconsin – madison': 'university of wisconsin - madison',
    'uw-madison': 'university of wisconsin - madison',
    'university of washington': 'university of washington',
    'washington university in st louis': 'university of washington',
    'paul g allen school of computer science & engineering university of washington':
    'university of washington',
    'university of washington seattle': 'university of washington',
    'department of computer science university of washington': 'university of washington',
    'dept of psychology ucsd': 'university of california san diego',
    'ucsd': 'university of california san diego',
    'uber ai': 'uber',
    'uber ai labs': 'uber',
    'uber advanced technologies group': 'uber',
    'uber': 'uber',
    'universite de montreal': 'universite de montreal',
    'mila université de montréal': 'universite de montreal',
    'mila polytechnique montréal': 'ecole polytechnique de montreal',
    'polytechnique montréal': 'ecole polytechnique de montreal',
    'cmap ecole polytechnique palaiseau france': 'ecole polytechnique',
    'cmap ecole polytechnique': 'ecole polytechnique',
    'ecole polytechnique': 'ecole polytechnique',
    'cmap école polytechnique': 'ecole polytechnique',
    'ecole normale superieure paris france': 'ecole normale superieure',
    'ecole normale superieure paris': 'ecole normale superieure',
    'école normale supérieure': 'ecole normale superieure',
    'group for neural theory ens paris': 'ecole normale superieure',
    'sorbonne université': 'sorbonne universite',
    'inria lille - nord europe': 'inria',
    'inria saclay': 'inria',
    'inria lille - nord europe team sequel': 'inria',
    'inria lille – nord europe': 'inria',
    'inria - sierra project-team': 'inria',
    'sequel team inria lille - nord europe france': 'inria',
    'sequel team inria lille – nord europe france': 'inria',
    'sequel team inria lille – nord europe': 'inria',
    'inria – sierra project-team': 'inria',
    'sequel project inria lille - nord europe france': 'inria',
    'inria lille - nord europe team sequel france': 'inria',
    'inria lille - team sequel': 'inria',
    'sequel team - inria lille': 'inria',
    'inria lille france': 'inria',
    'inria - willow project-team': 'inria',
    'lagrange umr 79  cnrs oca': 'cnrs',
    'irisa umr 67 cnrs': 'cnrs',
    'ibm tj watson research center': 'ibm research',
    'ibm almaden research center': 'ibm research',
    'ibm t j watson research center': 'ibm research',
    'ibm research ai': 'ibm research',
    'ibm watson research ctr': 'ibm research',
    'ibm thomas j watson research center': 'ibm research',
    'ibm research almaden': 'ibm research',
    'ibm research - tokyo': 'ibm research',
    'ibm research ny usa': 'ibm research',
    'ibm research – almaden': 'ibm research',
    'ibm research & mit-ibm watson ai lab': 'ibm research',
    'ibm research ireland': 'ibm research',
    'ibm research - ireland': 'ibm research',
    'ibm research - almaden': 'ibm research',
    'google deepmind': 'deepmind',
    'deepmind london': 'deepmind',
    'deepmind technologies': 'deepmind',
    'deepmind london uk': 'deepmind',
    'deepmind paris': 'deepmind',
    'kth ee school / acl': 'kth',
    'kth royal institute of technology': 'kth',
    'université paris-saclay': 'universite paris-saclay',
    'cmla ens paris-saclay': 'ecole normal superieure',
    'university of alberta canada': 'university of alberta',
    'department of computing science university of alberta edmonton ab t6g e8 canada':
    'university of alberta',
    'university of waterloo': 'university of waterloo',
    'university of waterloo canada': 'university of waterloo',
    'yahoo! labs': 'yahoo! research',
    'yahoo labs': 'yahoo! research',
    'yahoo research': 'yahoo! research',
    'department of ee kaist': 'kaist',
    'new york university': 'new york university',
    'nyu': 'new york university',
    'courant institute of mathematical sciences new york university': 'new york university',
    'courant institute new york university': 'new york university',
    'courant institute nyu': 'new york university',
    'polytechnic institute of new york university': 'new york university',
    'university at buffalo the state university of new york': 'suny at buffalo',
    'state university of new york at buffalo': 'suny at buffalo',
    'suny buffalo': 'suny at buffalo',
    'department of statistics columbia university': 'columbia university',
    'columbia university new york ny 7': 'columbia university',
    'columbia business school': 'columbia university',
    'columbia university new york ny 7 usa': 'columbia university',
    'columbia university new york ny': 'columbia university',
    'department of computer science university of british columbia':
    'university of british columbia',
    'korea advanced institute of science and technology': 'kaist',
    'department of brain and cognitive engineering korea university seoul korea':
    'korea university',
    'korea university korea seoul': 'korea university',
    'seoul national university seoul korea': 'seoul national university',
    'sungkyunkwan university suwon korea 69': 'sungkyunkwan university',
    'dept of computer science and engineering postech pohang korea':
    'pohang university of science and technology',
    'applied research korea gracenote inc': 'gracenote',
    'tsinghua university beijing 8 china': 'tsinghua university',
    'department of computer science and technology tsinghua university beijing 8 china':
    'tsinghua university',
    'iiis tsinghua university': 'tsinghua university',
    'tsinghua university beijing china': 'tsinghua university',
    'state key lab for intell tech & systems tsinghua university beijing china':
    'tsinghua university',
    'state key lab for intell tech & sys tsinghua university beijing china': 'tsinghua university',
    'nanjing university nanjing  china': 'nanjing university',
    'tencent ai lab china': 'tencent ai lab',
    'beijing normal university beijing 87 china': 'beijing normal university',
    'school of electronic engineering xidian university china': 'xidian university',
    'the chinese university of hong kong': 'chinese university of hong kong',
    'department of information engineering the chinese university of hong kong':
    'chinese university of hong kong',
    'hong kong university of science and technology hong kong china':
    'hong kong university of science and technology',
    'university of heidelberg heidelberg 69 germany': 'university of heidelberg',
    'university of freiburg germany': 'university of freiburg',
    'saarland university saarbrucken germany': 'saarland university',
    'saarland university saarbrücken germany': 'saarland university',
    'machine learning group tu berlin': 'technische universitat berlin',
    'tu berlin berlin germany': 'technische universitat berlin',
    'computer science tu berlin': 'technische universitat berlin',
    'tu dresden dresden germany': 'technische universitat dresden',
    'tu berlin': 'technische universitat berlin',
    'technische universität berlin': 'technische universitat berlin',
    'universidad carlos iii de madrid - spain': 'university carlos iii in madrid',
    'duke university durham nc 778': 'duke university',
    'department of electrical and computer engineering duke university': 'duke university',
    'statistics department duke university': 'duke university',
    'yandex moscow russia': 'yandex',
    'samsung ai centre cambridge uk': 'samsung ai',
    'samsung ai center moscow': 'samsung ai',
    'skolkovo institute of science and technology 6 moscow russia':
    'skolkovo institute of science and technology',
    'university of pennsylvania philadelphia pa usa': 'university of pennsylvania',
    'wharton u penn': 'university of pennsylvania',
    'school of electronics engineering and computer science peking university': 'peking university',
    'center for data science peking university': 'peking university',
    'univ of california irvine': 'university of california irvine',
    'usc': 'university of southern california',
    'univ of southern california': 'university of southern california',
    'univ of texas dallas': 'university of texas at dallas',
    'department of electrical and computer engineering texas a&m university':
    'texas a&m university',
    'princeton university nj 8': 'princeton university',
    'princeton university and institute for advanced study': 'princeton university',
    'department of operations research and financial engineering princeton university':
    'princeton university',
    'department of computer science princeton university': 'princeton university',
    '& princeton university': 'princeton university',
    'princeton university princeton nj 8': 'princeton university',
    'department of electrical engineering princeton university': 'princeton university',
    'nec laboratories america': 'nec corporation',
    'nec corporation': 'nec corporation',
    'nec laboratories': 'nec corporation',
    'nec labs america': 'nec corporation',
    'nec corporation the university of tokyo': 'nec corporation',
    'nec labs europe': 'nec corporation',
    'nec laboratories america inc': 'nec corporation',
    '()nec labs america princeton nj': 'nec corporation',
    'psl research university paris france': 'psl research university',
    'nvidia research': 'nvidia',
    'university college london uk': 'university college london',
    'gatsby unit ucl': 'university college london',
    'ucl': 'university college london',
    'imperial college london uk': 'imperial college london',
    'imperial college business school united kingdom': 'imperial college london',
    'college park md 7': 'college park',
    'college park md': 'college park',
    'college park md 7 usa': 'college park',
    'baylor college of medicine rice university': 'baylor college of medicine',
    'computer science dartmouth college': 'dartmouth college',
    'university of maryland baltimore county': 'university of maryland',
    'georgia tech': 'georgia institute of technology',
    'isye georgia institute of technology atlanta ga usa': 'georgia institute of technology',
    'georgia institute of technology atlanta ga  usa': 'georgia institute of technology',
    'computational science and engineering georgia institute of technology':
    'georgia institute of technology',
    'college of computing georgia institute of technology': 'georgia institute of technology',
    'university of illinois urbana-champaign': 'university of illinois at urbana-champaign',
    'university of illinois at urbana champaign': 'university of illinois at urbana-champaign',
    'psychology department university of illinois at urbana-champaign champaign il 68':
    'university of illinois at urbana-champaign',
    'university of illinois at urbana-champaign urbana il 68 usa':
    'university of illinois at urbana-champaign',
    'cambridge university': 'university of cambridge',
    'university of cambridge uk': 'university of cambridge',
    'university of cambridge cambridge uk': 'university of cambridge',
    'the alan turing institute': 'alan turing institute',
    'university of michigan ann arbor': 'university of michigan',
    'university of michigan ann arbor mi 89 usa': 'university of michigan',
    'university of michigan ann arbor usa': 'university of michigan',
    'michigan state university east lansing mi 88': 'michigan state university',
    'vector institute': 'university of toronto',
    'university of toronto vector institute': 'university of toronto',
    'department of computer science university of toronto': 'university of toronto',
    'department of statistics university of toronto': 'university of toronto',
    'national univ of singapore': 'national university of singapore',
    'national university of singapore singapore 776': 'national university of singapore',
    'national university of singapore singapore': 'national university of singapore',
    'university of california at berkeley': 'university of california berkeley',
    'department of engineering mathematics university of bristol': 'university of bristol',
    'department of computer science brown university providence ri 9': 'brown university',
    'department of computer science brown university providence ri': 'brown university',
    'department of computer science brown university': 'brown university',
    'gatsby computational neuroscience unit ucl': 'university college london',
    'intel ai lab': 'intel labs',
    'carnegie-mellon university': 'carnegie mellon university',
    'carnegie melon university': 'carnegie mellon university',
    'school of informatics university of edinburgh': 'university of edinburgh',
    'mccombs school of business': 'university of texas at austin',
    'school of computer science mcgill university': 'mcgill university',
    'graduate school of informatics kyoto university': 'kyoto university',
    'indian institute of science bangalore 6 india': 'indian institute of science bangalore',
    'indian institute of technology kanpur india': 'iit kanpur',
    'iit delhi hauz khas': 'iit delhi',
    'university of tokyo japan': 'university of tokyo',
    'lab hubert curien umr  f-': 'cnrs',
    'purdue university usa': 'purdue university',
    'mitsubishi electric research laboratories (merl)': 'mitsubishi electric research laboratories',
    'mitsubishi electric research labs (merl)': 'mitsubishi electric research laboratories',
    'skolkovo institute of science and technology  moscow russia':
    'skolkovo institute of science and technology',
    'weizmann institute': 'weizmann institute of science',
    'the hong kong polytechnic university hong kong': 'the hong kong polytechnic university',
    'machine intelligence technology alibaba group bellevue wa 98 usa': 'alibaba group',
    'collaborative innovation center of novel software technology and industrialization':
    'nanjing university',
    'department of computer science johns hopkins university': 'johns hopkins university',
    'the australian national university': 'australian national university',
    'nicta australian national university': 'australian national university',
    'australian national university': 'australian national university',
    'nicta the australian national university': 'australian national university',
    'deakin university australia': 'deakin university',
    'deakin university geelong australia': 'deakin university',
    'computer science department ben gurion university': 'ben gurion university',
    'epfl - cvlab': 'epfl',
    'department of management sciences the university of iowa iowa city ia  usa':
    'university of iowa',
    'university of wisconsin - madison': 'university of wisconsin-madison',
    'university of wisconsin': 'university of wisconsin-madison',
    'department of computer sciences university of wisconsin-madison':
    'university of wisconsin-madison',
    'cbcl mcgovern institute - massachusetts institute of technology': 'mit',
    'university of helsinki finland': 'university of helsinki',
    'department of computer science university of helsinki': 'university of helsinki',
    'psychology department university of illinois at urbana-champaign champaign il 8':
    'university of illinois at urbana-champaign',
    'university of illinois at urbana-champaign urbana il 8 usa':
    'university of illinois at urbana-champaign',
    'rutgers university piscataway nj 88': 'rutgers university',
    'university of heidelberg heidelberg 9 germany': 'university of heidelberg',
    'temple university philadelphia pa 9 usa': 'temple university',
    'sun yat-sen university guangzhou china': 'sun yat-sen university',
    'indian institute of science bangalore': 'indian institute of science',
    'indian institute of science bangalore  india': 'indian institute of science',
    'indian institute of technology bombay': 'iit bombay',
    'riken center for advanced intelligence project': 'riken aip',
    'riken': 'riken aip',
    'department of computing science university of alberta edmonton ab tg e8 canada':
    'university of alberta',
    'department of computing science university of alberta': 'university of alberta',
    'toyota technological institute': 'toyota technological institute at chicago',
    'toyota research institute': 'toyota technological institute at chicago',
    'arizona state university tempe az 887': 'arizona state university',
    'université de toulouse': 'universite de toulouse',
    'université toulouse  paul sabatier': 'universite de toulouse',
    'australian centre for robotic vision australia': 'australian centre for robotic vision',
    'electronics and information systems department (elis) ghent university': 'ghent university',
    'anu': 'australian national university',
    'national university of singapore singapore 77': 'national university of singapore',
    'netﬂix': 'netflix',
    'huawei technologies co ltd': 'huawei',
    'institute for theoretical computer science graz university of technology':
    'graz university of technology',
    'university of tehran tehran iran': 'university of tehran',
    'courant institute': 'new york university',
    'courant institute of mathematical sciences': 'new york university',
    'computer science and artiﬁcial intelligence lab massachusetts institute of technology': 'mit',
    'massachusetts institute of technology eecs': 'mit',
    'massachusetts institute of technology lincoln laboratory': 'mit',
    'massachussetts institute of technology': 'mit',
    'department of brain and cognitive sciences massachusetts institute of technology': 'mit',
    'electrical engineering & computer science massachusetts institute of technology': 'mit',
    'dept of electrical engineering and computer science massachusetts institute of technology usa':
    'mit',
    'department of eecs massachusetts institute of technology': 'mit',
    'center for brain science harvard university cambridge ma 8 usa': 'harvard university',
    'department of neurosurgery brigham and women’s hospital harvard medical school':
    'harvard university',
    'harvard university cambridge ma 8': 'harvard university',
    'speech and hearing bioscience and technology harvard university': 'harvard university',
    'harvard th chan school of public health': 'harvard university',
    'harvard seas': 'harvard university',
    'and center for brain science harvard university cambridge massachusetts 8 usa':
    'harvard university',
    'harvard college': 'harvard university',
    'school of engineering and applied science harvard university': 'harvard university',
    'harvard mit diffeo': 'harvard university',
    'center for brain science harvard university cambridge ma 8': 'harvard university',
    'princeton university / ias': 'princeton university',
    'ceecs at northwestern university dorfe at princeton university': 'princeton university',
    'princeton university department of computer science princeton nj 8': 'princeton university',
    'carl icahn laboratories #  princeton university': 'princeton university',
    'department of operations research and financial engineering princeton nj 8':
    'princeton university',
    'princeton univ': 'princeton university',
    'princeton neuroscience institute department of psychology princeton university':
    'princeton university',
    'computer science princeton university': 'princeton university',
    'princeton princeton plasma physics laboratory': 'princeton university',
    'institute for advanced study princeton': 'princeton university',
    'orfe - princeton university': 'princeton university',
    'princeton university usa': 'princeton university',
    'princeton neuroscience institute princeton university': 'princeton university',
    'department of electrical engineering princeton university nj usa': 'princeton university',
    'princeton neuroscience institute': 'princeton university',
    'siemens corporate technology princeton nj': 'siemens',
    'princeton university princeton nj usa': 'princeton university',
    'princeton university orfe': 'princeton university',
    'department of psychology and neuroscience institute princeton university princeton nj usa':
    'princeton university',
    'computer science department at princeton university': 'princeton university',
    'department of electrical engineering  neuroscience institute princeton university':
    'princeton university',
    'princeton neuroscience institute and department of psychology princeton university':
    'princeton university',
    'google ai princeton': 'google',
    'university of copenhagen denmark': 'university of copenhagen',
    'shanghai university of finance and economics': 'shanghai university'
}

INSTITUTIONS_DELETE = (
    'engineering drive madison wi 706', 'department of computer science',
    'department of statistics', 'stanford ca 90', 'dept of computer science', 'stanford ca 9',
    'stanford ca', 'stanford ca and mountain view ca', 'serra mall stanford ca 9', 'stanford usa',
    'engineering drive madison wi 76', 'electrical engineering', 'university park pa 68',
    'university park pa 68 usa', 'college park', 'college of information and computer sciences',
    'state college pa 68', 'university park pa usa', 'computer science department',
    'department of electrical and computer engineering',
    'school of computer science and engineering', 'school of computer science',
    'department of mathematics and computer science', 'computer science division',
    'school of electrical and computer engineering', 'department of mathematics',
    'the institute of statistical mathematics', 'department of electrical engineering',
    'department of engineering', 'department of operations research and financial engineering',
    'department of information systems', 'department of psychology', 'department of cs',
    'school of informatics', 'school of economics and management', 'school of cs and eng',
    'statistical laboratory cms', 'national engineering laboratory for big data software',
    'coordinated science laboratory', 'engineering drive madison wi 7',
    'computational vision and neuroscience', 'computational vision and neuroscience group',
    'salt lake city ut', 'state college pa 8', 'university park pa 8 usa', 'university park pa 8',
    'electrical and computer engineering',
    'department of electrical engineering and computer science', 'stanford ca 9 usa',
    'electrical and computer engineering')

INSTITUTION_PARSING_FIXES = {
    'google brain google inc': ['google brain', 'google inc'],
    'mit csail google research': ['mit', 'google research'],
    'mit csail & cbmm': ['mit csail', 'cbmm'],
    'google research and hebrew university': ['google research', 'hebrew university'],
    'tel aviv university and google': ['tel aviv university', 'google'],
    'uc berkeley / google': ['uc berkeley', 'google'],
    'courant institute and google research': ['courant institute', 'google research'],
    'idiap research institute & epfl': ['idiap research institute', 'epfl'],
    'university of zurich and eth zurich': ['university of zurich', 'eth zurich'],
    'ut austin  amazon': ['ut austin', 'amazon'],
    'ut austin amazon': ['ut austin', 'amazon'],
    'amazon and ut austin': ['amazon', 'ut austin'],
    'the university of texas at austin microsoft research india':
    ['the university of texas at austin', 'microsoft research india'],
    'amazon & university of texas at austin': ['amazon', 'university of texas at austin'],
    'university of california at berkeley university of texas at austin icsi':
    ['university of california berkeley', 'university of texas at austin'],
    'tti chicago and ut austin': ['tti chicago', 'ut austin'],
    'queensland university of technology and uc berkeley':
    ['queensland university of technology', 'uc berkeley'],
    'uc merced nvidia': ['uc merced', 'nvidia'],
    'mit and uc berkeley': ['mit', 'uc berkeley'],
    'university of cambridge the alan turing institute university of california los angeles': [
        'university of cambridge', 'the alan turing institute',
        'university of california los angeles'
    ],
    '(cid)eecs uc berkeley (cid)cs umass lowell': ['uc berkeley', 'umass lowell'],
    '(cid)eecs uc berkeley ∇ee tsinghua university': ['uc berkeley', 'tsinghua university'],
    'uc berkeley google': ['uc berkeley', 'google'],
    'uc berkeley & qut': ['uc berkeley', 'qut'],
    'university of california merced google': ['university of california merced', 'google'],
    'uc merced nvidia research': ['uc merced nvidia', 'research'],
    'microsoft research cambridge ma the university of california at irvine':
    ['microsoft research cambridge ma', 'the university of california at irvine'],
    'university of california irvine and the canadian institute for advanced research (cifar)':
    ['university of california irvine', 'the canadian institute for advanced research (cifar)'],
    'uc berkeley google brain': ['uc berkeley', 'google brain'],
    'openai & uc berkeley': ['openai', 'uc berkeley'],
    'uc merced and yahoo labs': ['uc merced', 'yahoo labs'],
    'covariantai & uc berkeley': ['covariantai', 'uc berkeley'],
    'university of california merced nvidia  carnegie mellon university':
    ['university of california merced', 'nvidia', 'carnegie mellon university'],
    'university of california berkeley and queensland university of technology':
    ['university of california berkeley', 'queensland university of technology'],
    'carnegie mellon university university of california berkeley peking university':
    ['carnegie mellon university', 'university of california berkeley', 'peking university'],
    'courant institute and google': ['courant institute', 'google'],
    'hebrew university and google research': ['hebrew university', 'google research'],
    'mit google research': ['mit', 'google research'],
    'mit media lab and mcgovern institute': ['mit media lab', 'mcgovern institute'],
    'mit csail & mit-ibm watson ai lab': ['mit csail', 'mit-ibm watson ai lab'],
    '(cid9) carnegie mellon university ♦ rice university':
    ['carnegie mellon university', 'rice university'],
    'data6 the australian national university and the university of sydney':
    ['university of sydney', 'australian national university'],
    'ecole centrale paris & inria saclay': ['ecole centrale paris', 'inria saclay'],
    'cnrs & sorbonne universite': ['cnrs', 'sorbonne universite'],
    'sorbonne université cnrs lip6 f-7 paris france': ['sorbonne université', 'cnrs', 'lip6'],
    'inria and university college london': ['inria', 'university college london'],
    'univ grenoble alpes cnrs inria lig': ['universite grenoble alpes', 'cnrs', 'inria'],
    'inria - ens': ['inria', 'ecole normale superieure'],
    'cea saclay and cnrs ura 6': ['cea saclay', 'cnrs'],
    'cnrs enpc esiee paris upem': ['cnrs', 'paristech', 'esiee', 'paris upem'],
    'university of cambridge and alan turing institute':
    ['university of cambridge', 'alan turing institute'],
    'irisa umr 7 cnrs': ['irisa', 'cnrs'],
    'cea saclay and cnrs ura': ['cea saclay', 'cnrs'],
    'sorbonne université cnrs lip f-7 paris france': ['sorbonne université', 'cnrs'],
    'data the australian national university and the university of sydney':
    ['australian national university', 'university of sydney'],
    'the australian national university & nicta': ['australian national university', 'nicta'],
    'chuo university riken aip jst presto': ['chuo university', 'riken aip', 'jst presto'],
    'inria & ens': ['inria', 'ens'],
    'anu & nicta': ['anu', 'nicta'],
    'cwi and leiden university': ['cwi', 'leiden university'],
    'nicta and anu': ['nicta', 'anu'],
    'google brain and crest ensae': ['google brain', 'crest'],
    'nicta and the university of nsw': ['nicta', 'university of nsw'],
    'university of nsw and nicta': ['university of nsw', 'nicta'],
    'hebrew university and google research tel-aviv': ['hebrew university', 'google research'],
    'lcsl massachusetts institute of technology & istituto italiano di tecnologia cambridge ma': [
        'mit', 'istituto italiano di tecnologia'
    ],
    'massachusetts institute of technology & istituto italiano di tecnologia': [
        'mit', 'istituto italiano di tecnologia'
    ],
    'princeton university  harvard psychology': ['princeton university', 'harvard university'],
    'twitter & harvard university': ['twitter', 'harvard university'],
    'google research & harvard university': ['harvard university', 'google research'],
    'harvard university facebook': ['harvard university', 'facebook'],
    'harvard university and twitter': ['twitter', 'harvard university'],
    'google brain and princeton': ['google brain', 'princeton university'],
    'princeton university university of rochester pennsylvania state university': [
        'princeton university', 'university of rochester', 'pennsylvania state university'
    ],
    'johns hopkins university harbin institute of technology princeton university': [
        'johns hopkins university', 'harbin institute of technology', 'princeton university'
    ],
    'princeton university and mit': ['princeton university', 'mit'],
    'princeton university ?tencent ai lab northwestern university ⇧georgia tech': [
        'princeton university', 'tencent ai lab', 'northwestern university', 'georgia tech'
    ],
    'princeton university tencent ai lab georgia tech': [
        'princeton university', 'tencent ai lab', 'georgia tech'
    ],
    'google brain and princeton university': ['princeton university', 'google brain'],
    'princeton university and google ai princeton': ['princeton university', 'google'],
    '#university of tübingen and max planck institute for intelligent systems tübingen germany': [
        'max planck institute', 'university of tübingen'
    ],
    'bar ilan university and google': ['bar ilan university', 'google'],
    'université de lorraine cnrs inria loria': ['universite de lorraine', 'cnrs', 'inria'],
    'univ rennes inria cnrs irisa': ['universite rennes', 'inria', 'cnrs', 'irisa'],
    'microsoft research and wharton u penn': ['microsoft research', 'wharton u penn'],
    '(cid9)australian national university (anu) and national ict australia (nicta) canberra australia':
    ['australian national university', 'nicta']
}

COMMON_TYPOS = {'institue': 'institute'}
